import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ApolloProvider from "@/components/providers/apollo-provider";
import AuthGuard from "@/components/auth/auth-guard";
import { Navbar } from "@/components/navbar/navbar";
import { userNavLinksData } from "@/components/navbar/data/user-nav-links-data";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <ApolloProvider>
            <AuthGuard>
              {/* <Navbar navLinks={userNavLinksData} /> */}
              {children}
            </AuthGuard>
          </ApolloProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
